-- banco de dados Associados
INSERT INTO ASSOCIADOS(NOME, CARGO, DATA_DE_NASCIMENTO, SEXO) VALUES ('Gustavo Betete', 'VEREADOR', '1996-10-25', 'MASCULINO');
INSERT INTO ASSOCIADOS(NOME, CARGO, DATA_DE_NASCIMENTO, SEXO) VALUES ('Gustavo Mello', 'PREFEITO', '2001-07-12', 'MASCULINO');
INSERT INTO ASSOCIADOS(NOME, CARGO, DATA_DE_NASCIMENTO, SEXO) VALUES ('Elaine Cristina', 'DEPUTADO_ESTADUAL', '1999-05-17', 'FEMININO');
INSERT INTO ASSOCIADOS(NOME, CARGO, DATA_DE_NASCIMENTO, SEXO) VALUES ('Danilo Miguel', 'DEPUTADO_FEDERAL', '2000-04-07', 'MASCULINO');
INSERT INTO ASSOCIADOS(NOME, CARGO, DATA_DE_NASCIMENTO, SEXO) VALUES ('Yhonathan Pavan', 'SENADOR', '1995-02-15', 'MASCULINO');
INSERT INTO ASSOCIADOS(NOME, CARGO, DATA_DE_NASCIMENTO, SEXO) VALUES ('Luciana Silva', 'GOVERNADOR', '1988-12-05', 'FEMININO');
INSERT INTO ASSOCIADOS(NOME, CARGO, DATA_DE_NASCIMENTO, SEXO) VALUES ('Matheus Cardoso', 'PRESIDENTE', '1999-05-12', 'MASCULINO');


--banco de dados Partido
INSERT INTO PARTIDOS(NOME_DO_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Partido dos Unidos da Vila Maria', 'PUVM', 'CENTRO', '1988-06-25');
INSERT INTO PARTIDOS(NOME_DO_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Partido dos Crediarios do Bolsa Familia', 'PCBF', 'ESQUERDA', '1980-02-10');
INSERT INTO PARTIDOS(NOME_DO_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Partido dos Conservadores Liberalistas', 'PCL', 'DIREITA', '2000-06-30');
INSERT INTO PARTIDOS(NOME_DO_PARTIDO, SIGLA, IDEOLOGIA, DATA_DE_FUNDACAO) VALUES ('Partido dos Desempregados', 'PD', 'CENTRO', '1980-11-16');